package com.techsource.mycheck.domain;
// Generated 3 Oct, 2016 5:18:34 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommonSurvey generated by hbm2java
 */
@Entity
@Table(name = "common_Survey", catalog = "mycheck")
public class CommonSurvey implements java.io.Serializable {

	private Integer id;
	private String name;
	private String state;
	private String status;
	private Date startDate;
	private Date endDate;
	private String description;
	private Date created;
	private Date modified;
	private Date deleted;
	private Set<CommonSurveyEmployee> commonSurveyEmployees = new HashSet<CommonSurveyEmployee>(0);
	private Set<CommonSurveyQuestionsRelation> commonSurveyQuestionsRelations = new HashSet<CommonSurveyQuestionsRelation>(
			0);
	private Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations = new HashSet<CommonSurveyQuestionEmployeeRelation>(
			0);

	private Set<CommonSurveySubmission> commonSurveySubmissions = new HashSet<CommonSurveySubmission>(0);

	public CommonSurvey() {
	}

	public CommonSurvey(String name, String state, String status, Date startDate, Date endDate, String description,
			Date created, Date modified, Date deleted, Set<CommonSurveyEmployee> commonSurveyEmployees,
			Set<CommonSurveyQuestionsRelation> commonSurveyQuestionsRelations,
			Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations,
			Set<CommonSurveySubmission> commonSurveySubmissions) {
		this.name = name;
		this.state = state;
		this.status = status;
		this.startDate = startDate;
		this.endDate = endDate;
		this.description = description;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
		this.commonSurveyEmployees = commonSurveyEmployees;
		this.commonSurveyQuestionsRelations = commonSurveyQuestionsRelations;
		this.commonSurveyQuestionEmployeeRelations = commonSurveyQuestionEmployeeRelations;
		this.commonSurveySubmissions = commonSurveySubmissions;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", length = 5)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endDate", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

		@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonSurvey",cascade=CascadeType.ALL)
	public Set<CommonSurveyEmployee> getCommonSurveyEmployees() {
		return this.commonSurveyEmployees;
	}

	public void setCommonSurveyEmployees(Set<CommonSurveyEmployee> commonSurveyEmployees) {
		this.commonSurveyEmployees = commonSurveyEmployees;
	}

		@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonSurvey",cascade=CascadeType.ALL)
	public Set<CommonSurveyQuestionsRelation> getCommonSurveyQuestionsRelations() {
		return this.commonSurveyQuestionsRelations;
	}

	public void setCommonSurveyQuestionsRelations(Set<CommonSurveyQuestionsRelation> commonSurveyQuestionsRelations) {
		this.commonSurveyQuestionsRelations = commonSurveyQuestionsRelations;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonSurvey",cascade=CascadeType.ALL)
	public Set<CommonSurveyQuestionEmployeeRelation> getCommonSurveyQuestionEmployeeRelations() {
		return this.commonSurveyQuestionEmployeeRelations;
	}

	public void setCommonSurveyQuestionEmployeeRelations(
			Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations) {
		this.commonSurveyQuestionEmployeeRelations = commonSurveyQuestionEmployeeRelations;
	}

	/**
	 * @return the commonSurveySubmissions
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonSurvey",cascade=CascadeType.ALL)
	public Set<CommonSurveySubmission> getCommonSurveySubmissions() {
		return commonSurveySubmissions;
	}

	/**
	 * @param commonSurveySubmissions the commonSurveySubmissions to set
	 */
	public void setCommonSurveySubmissions(Set<CommonSurveySubmission> commonSurveySubmissions) {
		this.commonSurveySubmissions = commonSurveySubmissions;
	}

}
