package com.techsource.mycheck.domain;
// Generated 3 Oct, 2016 5:18:34 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommonSurveyQuestions generated by hbm2java
 */
@Entity
@Table(name = "common_Survey_Questions", catalog = "mycheck")
public class CommonSurveyQuestions implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer rating;
	private Date created;
	private Date modified;
	private Date deleted;
	private Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations = new HashSet<CommonSurveyQuestionEmployeeRelation>(
			0);
	private Set<CommonSurveyQuestionsRelation> commonSurveyQuestionsRelations = new HashSet<CommonSurveyQuestionsRelation>(
			0);

	public CommonSurveyQuestions() {
	}

	public CommonSurveyQuestions(String name, Integer rating, Date created, Date modified, Date deleted,
			Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations,
			Set<CommonSurveyQuestionsRelation> commonSurveyQuestionsRelations) {
		this.name = name;
		this.rating = rating;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
		this.commonSurveyQuestionEmployeeRelations = commonSurveyQuestionEmployeeRelations;
		this.commonSurveyQuestionsRelations = commonSurveyQuestionsRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonSurveyQuestions",cascade=CascadeType.ALL)
	public Set<CommonSurveyQuestionEmployeeRelation> getCommonSurveyQuestionEmployeeRelations() {
		return this.commonSurveyQuestionEmployeeRelations;
	}

	public void setCommonSurveyQuestionEmployeeRelations(
			Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations) {
		this.commonSurveyQuestionEmployeeRelations = commonSurveyQuestionEmployeeRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonSurveyQuestions",cascade=CascadeType.ALL)
	public Set<CommonSurveyQuestionsRelation> getCommonSurveyQuestionsRelations() {
		return this.commonSurveyQuestionsRelations;
	}

	public void setCommonSurveyQuestionsRelations(Set<CommonSurveyQuestionsRelation> commonSurveyQuestionsRelations) {
		this.commonSurveyQuestionsRelations = commonSurveyQuestionsRelations;
	}

}
