package com.techsource.mycheck.domain;
// Generated 3 Oct, 2016 5:18:34 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommonSurveyQuestionsRelation generated by hbm2java
 */
@Entity
@Table(name = "common_Survey_Questions_relation", catalog = "mycheck")
public class CommonSurveyQuestionsRelation implements java.io.Serializable {

	private Integer id;
	private CommonSurvey commonSurvey;
	private CommonSurveyQuestions commonSurveyQuestions;
	private Date created;
	private Date modified;
	private Date deleted;

	public CommonSurveyQuestionsRelation() {
	}

	public CommonSurveyQuestionsRelation(CommonSurvey commonSurvey, CommonSurveyQuestions commonSurveyQuestions,
			Date created, Date modified, Date deleted) {
		this.commonSurvey = commonSurvey;
		this.commonSurveyQuestions = commonSurveyQuestions;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commonSurveyId")
	public CommonSurvey getCommonSurvey() {
		return this.commonSurvey;
	}

	public void setCommonSurvey(CommonSurvey commonSurvey) {
		this.commonSurvey = commonSurvey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "surveyQuestionId")
	public CommonSurveyQuestions getCommonSurveyQuestions() {
		return this.commonSurveyQuestions;
	}

	public void setCommonSurveyQuestions(CommonSurveyQuestions commonSurveyQuestions) {
		this.commonSurveyQuestions = commonSurveyQuestions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

}
