package com.techsource.mycheck.domain;
// Generated 9 Sep, 2016 6:31:52 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", catalog = "mycheck")
public class Division implements java.io.Serializable {

	private Integer id;
	private String name;
	private String status;
	private Date created;
	private Date modified;
	private Date deleted;
	private Set<Surveydetails> surveydetailses = new HashSet<Surveydetails>(0);
	private Set<EmployeeDivision> employeeDivisions = new HashSet<EmployeeDivision>(0);
	private Set<DivisionCompany> divisionCompanies = new HashSet<DivisionCompany>(0);
	private Set<DepartmentDivision> departmentDivisions = new HashSet<DepartmentDivision>(0);
	private Set<EmailRelation> emailRelations = new HashSet<EmailRelation>(0);
	public Division() {
	}

	public  Division(String name, String status, Date created, Date modified, Date deleted,
			Set<Surveydetails> surveydetailses, Set<EmployeeDivision> employeeDivisions,
			Set<DivisionCompany> divisionCompanies, Set<DepartmentDivision> departmentDivisions,
			Set<EmailRelation> emailRelations) {
		this.name = name;
		this.status = status;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
		this.surveydetailses = surveydetailses;
		this.employeeDivisions = employeeDivisions;
		this.divisionCompanies = divisionCompanies;
		this.departmentDivisions = departmentDivisions;
		this.emailRelations = emailRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

		@OneToMany(fetch = FetchType.LAZY, mappedBy = "division",cascade=CascadeType.ALL)

	public Set<Surveydetails> getSurveydetailses() {
		return this.surveydetailses;
	}

	public void setSurveydetailses(Set<Surveydetails> surveydetailses) {
		this.surveydetailses = surveydetailses;
	}

		@OneToMany(fetch = FetchType.LAZY, mappedBy = "division",cascade=CascadeType.ALL)

	public Set<EmployeeDivision> getEmployeeDivisions() {
		return this.employeeDivisions;
	}

	public void setEmployeeDivisions(Set<EmployeeDivision> employeeDivisions) {
		this.employeeDivisions = employeeDivisions;
	}

		@OneToMany(fetch = FetchType.LAZY, mappedBy = "division",cascade=CascadeType.ALL)

	public Set<DivisionCompany> getDivisionCompanies() {
		return this.divisionCompanies;
	}

	public void setDivisionCompanies(Set<DivisionCompany> divisionCompanies) {
		this.divisionCompanies = divisionCompanies;
	}

		@OneToMany(fetch = FetchType.LAZY, mappedBy = "division",cascade=CascadeType.ALL)

	public Set<DepartmentDivision> getDepartmentDivisions() {
		return this.departmentDivisions;
	}

	public void setDepartmentDivisions(Set<DepartmentDivision> departmentDivisions) {
		this.departmentDivisions = departmentDivisions;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "division",cascade=CascadeType.ALL)
	public Set<EmailRelation> getEmailRelations() {
		return this.emailRelations;
	}

	public void setEmailRelations(Set<EmailRelation> emailRelations) {
		this.emailRelations = emailRelations;
	}


}
