package com.techsource.mycheck.domain;
// Generated 20 Oct, 2016 3:35:33 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "mycheck")
public class Employee implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String phone;
	private String email;
	private String address;
	private Date created;
	private Date modified;
	private Date deleted;
	private String status;
	private String empId;
	private String lname;
	private Set<EmpQuaterTargetboard> empQuaterTargetboards = new HashSet<EmpQuaterTargetboard>(0);
	private Set<EmployeeGroup> employeeGroups = new HashSet<EmployeeGroup>(0);
	private Set<EmployeeDivision> employeeDivisions = new HashSet<EmployeeDivision>(0);
	private Set<SurveyEmployee> surveyEmployees = new HashSet<SurveyEmployee>(0);
	private Set<CommonSurveyEmployee> commonSurveyEmployees = new HashSet<CommonSurveyEmployee>(0);
	private Set<SurveyResult> surveyResults = new HashSet<SurveyResult>(0);
	private Set<LongTermGoalEmp> longTermGoalEmps = new HashSet<LongTermGoalEmp>(0);
	private Set<EmpLogin> empLogins = new HashSet<EmpLogin>(0);
	private Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations = new HashSet<CommonSurveyQuestionEmployeeRelation>(
			0);
	private Set<EmailgpEmployee> emailgpEmployees = new HashSet<EmailgpEmployee>(0);
	private Set<EmployeeDepartment> employeeDepartments = new HashSet<EmployeeDepartment>(0);
	private Set<EmployeeRole> employeeRoles = new HashSet<EmployeeRole>(0);

	public Employee() {
	}

	public Employee(String fname, String phone, String email, String address, Date created, Date modified, Date deleted,
			String status, String empId, String lname, Set<EmpQuaterTargetboard> empQuaterTargetboards,
			Set<EmployeeGroup> employeeGroups, Set<EmployeeDivision> employeeDivisions,
			Set<SurveyEmployee> surveyEmployees, Set<CommonSurveyEmployee> commonSurveyEmployees,
			Set<SurveyResult> surveyResults, Set<LongTermGoalEmp> longTermGoalEmps, Set<EmpLogin> empLogins,
			Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations,
			Set<EmailgpEmployee> emailgpEmployees, Set<EmployeeDepartment> employeeDepartments,
			Set<EmployeeRole> employeeRoles) {
		this.fname = fname;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
		this.status = status;
		this.empId = empId;
		this.lname = lname;
		this.empQuaterTargetboards = empQuaterTargetboards;
		this.employeeGroups = employeeGroups;
		this.employeeDivisions = employeeDivisions;
		this.surveyEmployees = surveyEmployees;
		this.commonSurveyEmployees = commonSurveyEmployees;
		this.surveyResults = surveyResults;
		this.longTermGoalEmps = longTermGoalEmps;
		this.empLogins = empLogins;
		this.commonSurveyQuestionEmployeeRelations = commonSurveyQuestionEmployeeRelations;
		this.emailgpEmployees = emailgpEmployees;
		this.employeeDepartments = employeeDepartments;
		this.employeeRoles = employeeRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fname", length = 45)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@Column(name = "status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "emp_id", length = 45)
	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@Column(name = "lname", length = 45)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<EmpQuaterTargetboard> getEmpQuaterTargetboards() {
		return this.empQuaterTargetboards;
	}

	public void setEmpQuaterTargetboards(Set<EmpQuaterTargetboard> empQuaterTargetboards) {
		this.empQuaterTargetboards = empQuaterTargetboards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<EmployeeGroup> getEmployeeGroups() {
		return this.employeeGroups;
	}

	public void setEmployeeGroups(Set<EmployeeGroup> employeeGroups) {
		this.employeeGroups = employeeGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<EmployeeDivision> getEmployeeDivisions() {
		return this.employeeDivisions;
	}

	public void setEmployeeDivisions(Set<EmployeeDivision> employeeDivisions) {
		this.employeeDivisions = employeeDivisions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<SurveyEmployee> getSurveyEmployees() {
		return this.surveyEmployees;
	}

	public void setSurveyEmployees(Set<SurveyEmployee> surveyEmployees) {
		this.surveyEmployees = surveyEmployees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<CommonSurveyEmployee> getCommonSurveyEmployees() {
		return this.commonSurveyEmployees;
	}

	public void setCommonSurveyEmployees(Set<CommonSurveyEmployee> commonSurveyEmployees) {
		this.commonSurveyEmployees = commonSurveyEmployees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<SurveyResult> getSurveyResults() {
		return this.surveyResults;
	}

	public void setSurveyResults(Set<SurveyResult> surveyResults) {
		this.surveyResults = surveyResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<LongTermGoalEmp> getLongTermGoalEmps() {
		return this.longTermGoalEmps;
	}

	public void setLongTermGoalEmps(Set<LongTermGoalEmp> longTermGoalEmps) {
		this.longTermGoalEmps = longTermGoalEmps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<EmpLogin> getEmpLogins() {
		return this.empLogins;
	}

	public void setEmpLogins(Set<EmpLogin> empLogins) {
		this.empLogins = empLogins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<CommonSurveyQuestionEmployeeRelation> getCommonSurveyQuestionEmployeeRelations() {
		return this.commonSurveyQuestionEmployeeRelations;
	}

	public void setCommonSurveyQuestionEmployeeRelations(
			Set<CommonSurveyQuestionEmployeeRelation> commonSurveyQuestionEmployeeRelations) {
		this.commonSurveyQuestionEmployeeRelations = commonSurveyQuestionEmployeeRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<EmailgpEmployee> getEmailgpEmployees() {
		return this.emailgpEmployees;
	}

	public void setEmailgpEmployees(Set<EmailgpEmployee> emailgpEmployees) {
		this.emailgpEmployees = emailgpEmployees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<EmployeeDepartment> getEmployeeDepartments() {
		return this.employeeDepartments;
	}

	public void setEmployeeDepartments(Set<EmployeeDepartment> employeeDepartments) {
		this.employeeDepartments = employeeDepartments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee", cascade=CascadeType.ALL)
	public Set<EmployeeRole> getEmployeeRoles() {
		return this.employeeRoles;
	}

	public void setEmployeeRoles(Set<EmployeeRole> employeeRoles) {
		this.employeeRoles = employeeRoles;
	}

}
