package com.techsource.mycheck.domain;
// Generated 9 Sep, 2016 6:31:52 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpQuaterTargetboard generated by hbm2java
 */
@Entity
@Table(name = "emp_quater_targetboard", catalog = "mycheck")
public class EmpQuaterTargetboard implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private Quaters quaters;
	private TargetBoard targetBoard;
	private String status;
	private String state;

	public EmpQuaterTargetboard() {
	}

	public EmpQuaterTargetboard(Employee employee, Quaters quaters, TargetBoard targetBoard, String status,
			String state) {
		this.employee = employee;
		this.quaters = quaters;
		this.targetBoard = targetBoard;
		this.status = status;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "emp_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quater_id")
	public Quaters getQuaters() {
		return this.quaters;
	}

	public void setQuaters(Quaters quaters) {
		this.quaters = quaters;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "targetboard_id")
	public TargetBoard getTargetBoard() {
		return this.targetBoard;
	}

	public void setTargetBoard(TargetBoard targetBoard) {
		this.targetBoard = targetBoard;
	}

	@Column(name = "status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "state", length = 6)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
