package com.techsource.mycheck.domain;
// Generated 20 Oct, 2016 4:47:39 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LongTermGoalEmp generated by hbm2java
 */
@Entity
@Table(name = "longTermGoal_emp", catalog = "mycheck")
public class LongTermGoalEmp implements java.io.Serializable {

	private Integer id;
	private Employee employee;
	private LongTermGoal longTermGoal;
	private Date created;
	private Date modified;
	private Date deleted;

	public LongTermGoalEmp() {
	}

	public LongTermGoalEmp(Employee employee, LongTermGoal longTermGoal, Date created, Date modified, Date deleted) {
		this.employee = employee;
		this.longTermGoal = longTermGoal;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empId")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "longTermGoal_id")
	public LongTermGoal getLongTermGoal() {
		return this.longTermGoal;
	}

	public void setLongTermGoal(LongTermGoal longTermGoal) {
		this.longTermGoal = longTermGoal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

}
