package com.techsource.mycheck.domain;
// Generated 9 Sep, 2016 6:31:52 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quaters generated by hbm2java
 */
@Entity
@Table(name = "quaters", catalog = "mycheck")
public class Quaters implements java.io.Serializable {

	private Integer id;
	private String year;
	private String name;
	private Date startDate;
	private Date endDate;
	private String created;
	private String modified;
	private Date deleted;
	private String status;
	private String state;
	private Set<EmpQuaterTargetboard> empQuaterTargetboards = new HashSet<EmpQuaterTargetboard>(0);

	public Quaters() {
	}

	public Quaters(String year, String name, Date startDate, Date endDate, String created, String modified,
			Date deleted, String status, String state, Set<EmpQuaterTargetboard> empQuaterTargetboards) {
		this.year = year;
		this.name = name;
		this.startDate = startDate;
		this.endDate = endDate;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
		this.status = status;
		this.state = state;
		this.empQuaterTargetboards = empQuaterTargetboards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "year", length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endDate", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "created", length = 45)
	public String getCreated() {
		return this.created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Column(name = "modified", length = 45)
	public String getModified() {
		return this.modified;
	}

	public void setModified(String modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@Column(name = "status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "state", length = 5)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quaters",cascade=CascadeType.ALL)

	public Set<EmpQuaterTargetboard> getEmpQuaterTargetboards() {
		return this.empQuaterTargetboards;
	}

	public void setEmpQuaterTargetboards(Set<EmpQuaterTargetboard> empQuaterTargetboards) {
		this.empQuaterTargetboards = empQuaterTargetboards;
	}

}
