package com.techsource.mycheck.domain;
// Generated 9 Sep, 2016 6:31:52 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Survey generated by hbm2java
 */
@Entity
@Table(name = "survey", catalog = "mycheck")
public class Survey implements java.io.Serializable {

	private Integer id;
	private String name;
	private String state;
	private String status;
	private Date startDate;
	private Date endDate;
	private Date created;
	private Date modified;
	private Date deleted;
	private String description;
	private Set<SurveySubmission> surveySubmissions = new HashSet<SurveySubmission>(0);
	private Set<Surveydetails> surveydetailses = new HashSet<Surveydetails>(0);
	private Set<SurveyEmployee> surveyEmployees = new HashSet<SurveyEmployee>(0);
	private Set<SurveyResult> surveyResults = new HashSet<SurveyResult>(0);
	private Set<SurveySurveyqstn> surveySurveyqstns = new HashSet<SurveySurveyqstn>(0);

	public Survey() {
	}

	public Survey(String name, String state, String status, Date startDate, Date endDate, Date created, Date modified,
			Date deleted, String description, Set<SurveySubmission> surveySubmissions,
			Set<Surveydetails> surveydetailses, Set<SurveyEmployee> surveyEmployees, Set<SurveyResult> surveyResults,
			Set<SurveySurveyqstn> surveySurveyqstns) {
		this.name = name;
		this.state = state;
		this.status = status;
		this.startDate = startDate;
		this.endDate = endDate;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
		this.description = description;
		this.surveySubmissions = surveySubmissions;
		this.surveydetailses = surveydetailses;
		this.surveyEmployees = surveyEmployees;
		this.surveyResults = surveyResults;
		this.surveySurveyqstns = surveySurveyqstns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", length = 5)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endDate", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey",cascade=CascadeType.ALL)

	public Set<Surveydetails> getSurveydetailses() {
		return this.surveydetailses;
	}

	public void setSurveydetailses(Set<Surveydetails> surveydetailses) {
		this.surveydetailses = surveydetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey",cascade=CascadeType.ALL)

	public Set<SurveyEmployee> getSurveyEmployees() {
		return this.surveyEmployees;
	}

	public void setSurveyEmployees(Set<SurveyEmployee> surveyEmployees) {
		this.surveyEmployees = surveyEmployees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey",cascade=CascadeType.ALL)

	public Set<SurveyResult> getSurveyResults() {
		return this.surveyResults;
	}

	public void setSurveyResults(Set<SurveyResult> surveyResults) {
		this.surveyResults = surveyResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey",cascade=CascadeType.ALL)

	public Set<SurveySurveyqstn> getSurveySurveyqstns() {
		return this.surveySurveyqstns;
	}

	public void setSurveySurveyqstns(Set<SurveySurveyqstn> surveySurveyqstns) {
		this.surveySurveyqstns = surveySurveyqstns;
	}

	/**
	 * @return the surveySubmissions
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "survey",cascade=CascadeType.ALL)

	public Set<SurveySubmission> getSurveySubmissions() {
		return surveySubmissions;
	}

	/**
	 * @param surveySubmissions the surveySubmissions to set
	 */
	public void setSurveySubmissions(Set<SurveySubmission> surveySubmissions) {
		this.surveySubmissions = surveySubmissions;
	}

}
