package com.techsource.mycheck.domain;
// Generated 7 Oct, 2016 3:12:23 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SurveySubmission generated by hbm2java
 */
@Entity
@Table(name = "surveySubmission", catalog = "mycheck")
public class SurveySubmission implements java.io.Serializable {

	private Integer id;
	private Survey survey;
	private Integer totalEmployee;
	private Integer participatedEmployee;
	private Integer unparticipatedEmp;
	private String participatedPerc;
	private String status;
	private Date created;
	private Date modified;
	private Date deleted;

	public SurveySubmission() {
	}

	public SurveySubmission(Survey survey, Integer totalEmployee, Integer participatedEmployee,
			Integer unparticipatedEmp, String participatedPerc, String status, Date created, Date modified,
			Date deleted) {
		this.survey = survey;
		this.totalEmployee = totalEmployee;
		this.participatedEmployee = participatedEmployee;
		this.unparticipatedEmp = unparticipatedEmp;
		this.participatedPerc = participatedPerc;
		this.status = status;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sid")
	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	@Column(name = "totalEmployee")
	public Integer getTotalEmployee() {
		return this.totalEmployee;
	}

	public void setTotalEmployee(Integer totalEmployee) {
		this.totalEmployee = totalEmployee;
	}

	@Column(name = "participatedEmployee")
	public Integer getParticipatedEmployee() {
		return this.participatedEmployee;
	}

	public void setParticipatedEmployee(Integer participatedEmployee) {
		this.participatedEmployee = participatedEmployee;
	}

	@Column(name = "unparticipatedEmp")
	public Integer getUnparticipatedEmp() {
		return this.unparticipatedEmp;
	}

	public void setUnparticipatedEmp(Integer unparticipatedEmp) {
		this.unparticipatedEmp = unparticipatedEmp;
	}

	@Column(name = "participatedPerc", length = 50)
	public String getParticipatedPerc() {
		return this.participatedPerc;
	}

	public void setParticipatedPerc(String participatedPerc) {
		this.participatedPerc = participatedPerc;
	}

	@Column(name = "status", length = 5)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

}
