package com.techsource.mycheck.domain;
// Generated 3 Oct, 2016 5:18:34 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SurveyQuestion generated by hbm2java
 */
@Entity
@Table(name = "surveyQuestion", catalog = "mycheck")
public class SurveyQuestion implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer rating;
	private Date created;
	private Date deleted;
	private Date modified;
	private Set<SurveyResult> surveyResults = new HashSet<SurveyResult>(0);
	private Set<SurveySurveyqstn> surveySurveyqstns = new HashSet<SurveySurveyqstn>(0);

	public SurveyQuestion() {
	}

	public SurveyQuestion(String name, Integer rating, Date created, Date deleted, Date modified,
			Set<SurveyResult> surveyResults, Set<SurveySurveyqstn> surveySurveyqstns) {
		this.name = name;
		this.rating = rating;
		this.created = created;
		this.deleted = deleted;
		this.modified = modified;
		this.surveyResults = surveyResults;
		this.surveySurveyqstns = surveySurveyqstns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "surveyQuestion")
	public Set<SurveyResult> getSurveyResults() {
		return this.surveyResults;
	}

	public void setSurveyResults(Set<SurveyResult> surveyResults) {
		this.surveyResults = surveyResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "surveyQuestion")
	public Set<SurveySurveyqstn> getSurveySurveyqstns() {
		return this.surveySurveyqstns;
	}

	public void setSurveySurveyqstns(Set<SurveySurveyqstn> surveySurveyqstns) {
		this.surveySurveyqstns = surveySurveyqstns;
	}

}
