package com.techsource.mycheck.domain;
// Generated 9 Sep, 2016 6:31:52 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TargetQuestions generated by hbm2java
 */
@Entity
@Table(name = "target_questions", catalog = "mycheck")
public class TargetQuestions implements java.io.Serializable {

	private Integer id;
	private String name;
	private Byte status;
	private Date created;
	private Date modified;
	private Date deleted;
	private String description;
	private Set<TargetboardTargetquestions> targetboardTargetquestionses = new HashSet<TargetboardTargetquestions>(0);

	public TargetQuestions() {
	}

	public TargetQuestions(String name, Byte status, Date created, Date modified, Date deleted, String description,
			Set<TargetboardTargetquestions> targetboardTargetquestionses) {
		this.name = name;
		this.status = status;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
		this.description = description;
		this.targetboardTargetquestionses = targetboardTargetquestionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "targetQuestions",cascade=CascadeType.ALL)

	public Set<TargetboardTargetquestions> getTargetboardTargetquestionses() {
		return this.targetboardTargetquestionses;
	}

	public void setTargetboardTargetquestionses(Set<TargetboardTargetquestions> targetboardTargetquestionses) {
		this.targetboardTargetquestionses = targetboardTargetquestionses;
	}

}
