package com.techsource.mycheck.domain;
// Generated 9 Sep, 2016 6:31:52 PM by Hibernate Tools 5.1.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TargetBoard generated by hbm2java
 */
@Entity
@Table(name = "target_board", catalog = "mycheck")
public class TargetBoard implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private String status;
	private Date created;
	private Date modified;
	private Date deleted;
	private String state;
	private Set<TargetboardTargetquestions> targetboardTargetquestionses = new HashSet<TargetboardTargetquestions>(0);
	private Set<EmpQuaterTargetboard> empQuaterTargetboards = new HashSet<EmpQuaterTargetboard>(0);

	public TargetBoard() {
	}

	public TargetBoard(String name, String description, String status, Date created, Date modified, Date deleted,
			String state, Set<TargetboardTargetquestions> targetboardTargetquestionses,
			Set<EmpQuaterTargetboard> empQuaterTargetboards) {
		this.name = name;
		this.description = description;
		this.status = status;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
		this.state = state;
		this.targetboardTargetquestionses = targetboardTargetquestionses;
		this.empQuaterTargetboards = empQuaterTargetboards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@Column(name = "state", length = 5)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "targetBoard",cascade=CascadeType.ALL)

	public Set<TargetboardTargetquestions> getTargetboardTargetquestionses() {
		return this.targetboardTargetquestionses;
	}

	public void setTargetboardTargetquestionses(Set<TargetboardTargetquestions> targetboardTargetquestionses) {
		this.targetboardTargetquestionses = targetboardTargetquestionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "targetBoard",cascade=CascadeType.ALL)

	public Set<EmpQuaterTargetboard> getEmpQuaterTargetboards() {
		return this.empQuaterTargetboards;
	}

	public void setEmpQuaterTargetboards(Set<EmpQuaterTargetboard> empQuaterTargetboards) {
		this.empQuaterTargetboards = empQuaterTargetboards;
	}

}
