package com.techsource.mycheck.domain;
// Generated 9 Sep, 2016 6:31:52 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TargetboardTargetquestions generated by hbm2java
 */
@Entity
@Table(name = "targetboard_targetquestions", catalog = "mycheck")
public class TargetboardTargetquestions implements java.io.Serializable {

	private Integer id;
	private TargetBoard targetBoard;
	private TargetQuestions targetQuestions;
	private Date created;
	private Date modified;
	private Date deleted;

	public TargetboardTargetquestions() {
	}

	public TargetboardTargetquestions(TargetBoard targetBoard, TargetQuestions targetQuestions, Date created,
			Date modified, Date deleted) {
		this.targetBoard = targetBoard;
		this.targetQuestions = targetQuestions;
		this.created = created;
		this.modified = modified;
		this.deleted = deleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tb_id")
	public TargetBoard getTargetBoard() {
		return this.targetBoard;
	}

	public void setTargetBoard(TargetBoard targetBoard) {
		this.targetBoard = targetBoard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tq_id")
	public TargetQuestions getTargetQuestions() {
		return this.targetQuestions;
	}

	public void setTargetQuestions(TargetQuestions targetQuestions) {
		this.targetQuestions = targetQuestions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted", length = 0)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

}
